### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by zvezdochiot** [mnhrdt/ccmath#3]
Public Domain Mark 1.0:

https://github.com/ImageProcessing-ElectronicPublications/jpegrescan-perl/blob/master/LICENSE

https://creativecommons.org/licenses/mark/1.0/

Not?

**Comment by mnhrdt** [comment]
Why? this code was published under the LGPL license.

**Comment by zvezdochiot** [comment]
>LGPL

No problems. I just asked.
